version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clientdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  client-data-backend:
    build: ../client-data-service/backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  logging-backend:
    build: ../logging-service/backend
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka

  client-data-frontend:
    build: ../client-data-service/frontend
    ports:
      - "8081:80"
    depends_on:
      - client-data-backend

  logging-frontend:
    build: ../logging-service/frontend
    ports:
      - "8083:80"
    depends_on:
      - logging-backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - client-data-frontend
      - logging-frontend

volumes:
  postgres_data:
